version: "3"
services:
  app:
    image: www
    container_name: www
    build:
      context: .
    env_file:
      - .docker.env
    volumes:
      - ./init-scripts/:/init-scripts/
    ports:
      - 8080:80
    depends_on:
      - 'mysql'
    entrypoint:
      - /init-scripts/apache_start.sh
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: kudo_db
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    ports:
      - 13306:3306
  phpmyadmin:
    container_name: 'phpmyadmin'
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - '8081:80'
    environment:
      - 'PMA_HOST=mysql'
    depends_on:
      - 'mysql'
  node:
    image: node:10-alpine
    container_name: node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./init-scripts/:/init-scripts/
    entrypoint:
      - /init-scripts/node_start.sh
    depends_on:
      - 'app'
volumes:
  mysql:
    driver: "local"
